# Generated by Django 6.0.5 on 2026-05-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('REVIEW', 'Review'), ('REVISION', 'Revision'), ('APPROVED', 'Approved'), ('COMPLETED', 'Completed')], default='TODO', max_length=20),
        ),
    ]
