# Generated by Django 6.0.5 on 2026-05-24 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_task_status'),
        ('users', '0002_studio_user_studio'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='studio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='users.studio'),
        ),
    ]
