# Generated by Django 6.0.5 on 2026-05-25 00:10

from django.conf import settings
from django.db import migrations, models


def copy_assignees(apps, schema_editor):
    Task = apps.get_model('projects', 'Task')
    for task in Task.objects.exclude(assigned_to__isnull=True).iterator():
        task.assignees.add(task.assigned_to_id)


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_members'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assignees',
            field=models.ManyToManyField(related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(copy_assignees, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='task',
            name='assigned_to',
        ),
    ]
